### ISSUE TITLE
Performance log

### ISSUE THREAD

**Issue by eguil** [eguil/Density_bining#17]
IPSL-CM5A-LR (size=142x180x31) 240 months:
--> time chunk (bounds) =  1  ( 120 239 )
     read, rhon compute and array init CPU, elapsed: 158.56 164.945918083
   CPU of zonal mean compute and write = 5400 to 5700

 Max memory use 14.534416 GB
 Ratio to grid_nyears 0.864466643986 kB/unit(size_nyears)
 CPU use, elapsed 13244.36 13324.694025
 Ratio to grid_nyears 65.6448083922 1.e-6 sec/unit(size_nyears)
480 months: 25000 sec

Whole historical IPSL-CM5A-LR (15 chunks)
Max memory use 15.743244 GB
 Ratio to grid_nyears 0.120046714323 kB/unit(size_nyears)
 CPU use, elapsed 90416.31 90524.376164
 Ratio to grid_nyears 57.4541738703 1.e-6 sec/unit(size_nyears)

====15/8===============================================
AFTER regrid optimisation (divided CPU by factor 25 !)
60 months of IPSL:
   CPU of density bining = 55.12
   CPU of annual mean compute = 101.98
   CPU of persistence compute = 8.55
   CPU of interpolation = 14.84
   CPU of zonal mean = 12.31

 Max memory use 6.488676 GB
 Ratio to grid_nyears 1.54371361481 kB/unit(size_nyears)
 CPU use, elapsed 210.3 210.91753912
 Ratio to grid_nyears 4.16935305439 1.e-6 sec/unit(size_nyears)

=====21/8==========================================
Test IPSL 150 yrs / tcdel = 24 months
(as 120 month was ~11 1.e-6 sec/unit(size*nyears) instead of 4)
--> time chunk (bounds) =  77  ( 1848 1871 )
 Change unit to celsius
      t =  0
      t =  20
   CPU of density bining      = 48.46
   CPU of annual mean compute = 118.84
   CPU of interpolation       = 10.75
   CPU of zonal mean          = 5.0
   CPU of persistence compute = 6.13
   CPU of chunk               = 189.24

 Max memory use 4.42816 GB
 Ratio to grid_nyears 0.0337659797749 kB/unit(size_nyears)
 CPU use, elapsed 13401.89 13704.4979579
 Ratio to grid_nyears 8.51610199808 1.e-6 sec/unit(size_nyears)

Test GFDL 180 yrs tcdel = 24 months
 --> time chunk (bounds) =  89  ( 2136 2159 )
   CPU of density bining      = 133.85
   CPU of annual mean compute = 258.1
   CPU of interpolation       = 9.35
   CPU of zonal mean          = 4.37
   CPU of persistence compute = 6.88
   CPU of chunk               = 412.62

 Max memory use 11.95226 GB
 Ratio to grid_nyears 0.018444845679 kB/unit(size_nyears)
 CPU use, elapsed 41961.19 42853.3485019
 Ratio to grid_nyears 5.39624356996 1.e-6 sec/unit(size_nyears)

---------- 24/8 -------------------------------------
Latest persist computation perfs:
MPI-ESM-LR:
 --> time chunk (bounds) =  77  ( 1848 1871 )
     Change unit to celsius
   CPU of density bining      = 97.36
   CPU of annual mean compute = 44.49
   CPU of interpolation       = 9.53
   CPU of zonal mean          = 13.69
   CPU of persistence compute = 154.26
   CPU of chunk               = 319.39

 Max memory use 8.5064 GB
 Ratio to grid_nyears 0.0242046365093 kB/unit(size_nyears)
 CPU use, elapsed 32165.43 32620.374727
 Ratio to grid_nyears 7.62712527544 1.e-6 sec/unit(size_nyears)

IPSL-CM5A-LR:
--> time chunk (bounds) =  14  ( 1680 1799 )
     Change unit to celsius
   CPU of density bining      = 321.79
   CPU of annual mean compute = 168.69
   CPU of interpolation       = 65.25
   CPU of zonal mean          = 198.75
   CPU of persistence compute = 765.64
   CPU of chunk               = 1520.23

 Max memory use 18.730868 GB
 Ratio to grid_nyears 0.142828197277 kB/unit(size_nyears)
 CPU use, elapsed 21304.62 21387.40253
 Ratio to grid_nyears 13.5378157074 1.e-6 sec/unit(size_nyears)

GFDL CM2.1:
 --> time chunk (bounds) =  89  ( 2136 2159 )
   CPU of density bining      = 142.02
   CPU of annual mean compute = 50.83
   CPU of interpolation       = 9.56
   CPU of zonal mean          = 13.51
   CPU of persistence compute = 201.95
   CPU of chunk               = 417.94

 Max memory use 11.90534 GB
 Ratio to grid_nyears 0.0183724382716 kB/unit(size_nyears)
 CPU use, elapsed 44609.81 45065.6246371
 Ratio to grid_nyears 5.73685828189 1.e-6 sec/unit(size_nyears)

**Comment by durack1** [comment]
Deprecated by #33
