### ISSUE TITLE
Surface density transformation

### ISSUE THREAD

**Issue by eguil** [eguil/Density_bining#18]
Compute density bined buoyancy flux, transformation and formation (a la Walin 1982)
Create specific proc surface_transf.py
Will require E-P (wfo) and net downward heat flux over oceans (fields TBD)
![screen shot 2014-09-08 at 21 15 43](https://cloud.githubusercontent.com/assets/7075402/4191305/9177c96a-378c-11e4-9b27-023fbcd68106.jpg)

**Comment by eguil** [comment]
Back to surface transformation with the arrival of Victor Estella-Perez (LOCEAN Post-doc).

**Comment by durack1** [comment]
@eguil great!
