### ISSUE TITLE
Interpolation or masking bug ?

### ISSUE THREAD

**Issue by eguil** [eguil/Density_bining#35]
@durack1 Can you investigate this and push through UVCDAT

IPSL/ORCA grid is distorted where the spuriously masked points appear on the target grid
Using:     

```
ESMP.ESMP_Initialize()
regridObj = CdmsRegrid(ingrid,outgrid,depth_bin.dtype,missing=valmask,regridMethod='bicubic',regridTool='esmf')
```

using regridMethod = 'linear' same pb
![screen shot 2015-02-05 at 11 54 14](https://cloud.githubusercontent.com/assets/7075402/6059074/d0fc45e0-ad2d-11e4-9f80-583b240742e7.jpg)

**Comment by durack1** [comment]
@doutriaux1 it's likely there is some work to figure out within ESMF here..?

**Comment by eguil** [comment]
Figure above is doing ncview on field isondepthg from file /work/guilyardi/Density_bining/test>cmip5.IPSL-CM5A-LR.historical.r1i1p1.an.ocn.Omon.density.ver-v20111119-compressed_old.nc

**Comment by eguil** [comment]
also see issues #53 and #54

**Comment by eguil** [comment]
Taken up by #54 and #53
