### ISSUE TITLE
Parallel version of key loop in binDensity.py

### ISSUE THREAD

**Issue by eguil** [eguil/Density_bining#37]
@momipsl @durack1 
Goal is to reduce elapsed time of "75% loop"

**Comment by eguil** [comment]
First attempt by Mark:
Eric

OK thanks for this information, so the data types are all standard that simplifies things.

Regarding LonN*LatN.  In the code the number of process to spin off is determined by the list comprehension at line 1485:
[i for i in range(lonN * latN) if nomask[i]] 

Can you give me an estimation of the length of this array as this gives us the number of processes to execute in parallel.

Regards

Mark

**Comment by eguil** [comment]
@momipsl LonN*LatN is typically 30 000 to 100 000 (with 30% of masked points)

**Comment by eguil** [comment]
From Mark:

OK I have just committed an UNTESTED implementation of a multi-threaded depth interpolation. This implementation places the interpolations to be performed in a task queue. Task workers then perform the interpolations on separate threads.

At line 1472 the variable MAX_THREADS is declared, this is the maximum number of threads to be created. You may wish to experiment with this number, i.e. run a test, increment MAX_THREADS, run the test again. At some point you will see that the job time reaches a plateau (and may even increase) as the cost of thread switching exceeds the savings from parallelising the interpolation.

Note that this implementation is untested and furthermore it is predicated upon numpy supporting concurrent access to arrays. It is uncertain whether all input data types are indeed thread safe if not then we will need to extend this implementation so that all variable access is via explicit thread locks.

**Comment by eguil** [comment]
ok first tests:
1) missing args c1_s and c2_s in call from main code
2) crashes with:
 
    Traceback (most recent call last):
      File "/home/ericglod/Density_bining/density-bin-parallel/drive_ACCESS1-0.py", line 39, in <module>
        densityBin(modelThetao,modelSo,modelAreacello,outfileDensity,timeint='1,12')
      File "/home/ericglod/Density_bining/density-bin-parallel/binDensity.py", line 684, in densityBin
        valmask)
      File "/home/ericglod/Density_bining/density-bin-parallel/binDensity.py", line 1476, in  _parallellize_interpolate_depth
        task_q = Queue(maxsize=0)
    NameError: global name 'Queue' is not defined

**Comment by momipsl** [comment]
Just committed update that correctly imports the python modules queue and threading.

**Comment by momipsl** [comment]
Considering the size of LonN*LatN (i.e. 30k - 100k) then we will probably have to process these in batches using generators.  I will await results of tests before implementing this.

**Comment by eguil** [comment]
could not find a new commit...

**Comment by durack1** [comment]
It was committed to your eguil/Density_bining repo directly:
https://github.com/eguil/Density_bining/blob/master/binDensity.py#L45-46

**Comment by eguil** [comment]
oups, I'd rather we keep two separate branches as we are using the 
standardversion
How can we come back to the previous state ?

On 6/3/15 20:09, Paul J. Durack wrote:
>
> It was committed to your eguil/Density_bining repo directly:
> https://github.com/eguil/Density_bining/blob/master/binDensity.py#L45-46
>
> â
> Reply to this email directly or view it on GitHub 
> <https://github.com/eguil/Density_bining/issues/37#issuecomment-77616757>.
>

-- 
Eric Guilyardi
IPSL/LOCEAN - Dir. Rech. CNRS
Tour 45, 4eme, piece 406
UPMC, case 100
4 place Jussieu, F-75252 Paris
Tel: +33 (0)1 44 27 70 76 	Prof. Eric Guilyardi
NCAS Climate
Meteorology Department
University of Reading
Reading RG6 6BB - UK
Tel: +44 (0)118 378 8315

                 http://ncas-climate.nerc.ac.uk/~ericg

**Comment by durack1** [comment]
@eguil you'll have to revert the commit - and then turn off write access to your repo, so we then have to issue pull requests from our respective forks..

**Comment by eguil** [comment]
right I need help with git commands here...

On 6/3/15 20:18, Paul J. Durack wrote:
>
> @eguil <https://github.com/eguil> you'll have to revert the commit - 
> and then turn off write access to your repo, so we then have to issue 
> pull requests from our respective forks..
>
> â
> Reply to this email directly or view it on GitHub 
> <https://github.com/eguil/Density_bining/issues/37#issuecomment-77618469>.
>

-- 
Eric Guilyardi
IPSL/LOCEAN - Dir. Rech. CNRS
Tour 45, 4eme, piece 406
UPMC, case 100
4 place Jussieu, F-75252 Paris
Tel: +33 (0)1 44 27 70 76 	Prof. Eric Guilyardi
NCAS Climate
Meteorology Department
University of Reading
Reading RG6 6BB - UK
Tel: +44 (0)118 378 8315

                 http://ncas-climate.nerc.ac.uk/~ericg

**Comment by durack1** [comment]
@eguil did you want me to do a revert here? I'll get binDensity.py back to pre-threads version and rename the threaded version binDensityMP.py - is that ok?

I'll then issue you a pull request so you can review and then merge changes back in..

**Comment by eguil** [comment]
@momipsl

that would be great - thanks !
The binDensityMP.py code is now running and producing results that are 
correct - but I don't see any speed up yet.
Making further tests with using more nodes/cpus.

On 6/3/15 20:32, Paul J. Durack wrote:
>
> @eguil <https://github.com/eguil> did you want me to do a revert here? 
> I'll get binDensity.py back to pre-threads version and rename the 
> threaded version binDensityMP.py - is that ok?
>
> I'll then issue you a pull request so you can review and then merge 
> changes back in..
>
> â
> Reply to this email directly or view it on GitHub 
> <https://github.com/eguil/Density_bining/issues/37#issuecomment-77620833>.
>

-- 
Eric Guilyardi
IPSL/LOCEAN - Dir. Rech. CNRS
Tour 45, 4eme, piece 406
UPMC, case 100
4 place Jussieu, F-75252 Paris
Tel: +33 (0)1 44 27 70 76 	Prof. Eric Guilyardi
NCAS Climate
Meteorology Department
University of Reading
Reading RG6 6BB - UK
Tel: +44 (0)118 378 8315

                 http://ncas-climate.nerc.ac.uk/~ericg

**Comment by durack1** [comment]
@eguil did I need to do anything here, or are you ok? If I need to do something just let me know (and what that is)

**Comment by durack1** [comment]
@eguil did you want me to reinstate the old binDensity.py - did you want to commit binDensityMP.py to the repo?

**Comment by eguil** [comment]
Here are the results I have with the current threaded version. Either not doing what is expected or I am not using it right:

     standard code: CPU use, elapsed 328.99 632.229090929
     threaded code (1 node 1 CPU) : CPU use, elapsed 300.6 672.093030214
     threaded code (1 node 8 CPU) : CPU use, elapsed 739.82 851.112504959
     threaded code (2 nodes 8 CPU): CPU use, elapsed 1154.07 1242.90578103

**Comment by eguil** [comment]
Paul, yes please revert back to version without parallel in github ( create binDensityMP.py as described in your comment above). I though it was Mark sending this as when you get the email you don't know who wrote the comment ! I need help to do this as I don;t know github well enough.

**Comment by durack1** [comment]
@eguil this should sort things out https://github.com/eguil/Density_bining/pull/38

**Comment by momipsl** [comment]
Upon conducting a review it is clear that the current implementation of parallelisation leveraging python's threading module will not result in any performance gains.  This is due to the python GIL which blocks CPU intensive threads span from the same process.  This technique would work fine if the work to be performed was I/O based rather than CPU based.

Therefore the implementation must revert back to leveraging python's multiprocessing module.  This complicates the code as the arrays being processed will need to be copied to/from shared memory data structures.  I will endeavour to commit an initial implementation of this in the next day or so.

**Comment by eguil** [comment]
Thanks Mark. This would explain the result I summarised above. Can you please develop in binDensityMP.py from now on ?

**Comment by momipsl** [comment]
New implementation of binDensityMP.py  This uses python multiprocessing library to parallelize the interpolations.  The arrays (c1m, c2m, s_s, szm, zzm) are placed in shared memory so that they do not need to be copied to the spawned processes.

Note - this is UNTESTED !

**Comment by eguil** [comment]
Hi Mark: result from first test:

Traceback (most recent call last):
  File "/home/ericglod/Density_bining/drive_CSIRO_piC.py", line 34, in <module>
    densityBin(modelThetao,modelSo,modelAreacello,outfileDensity,timeint='1,12')
  File "/home/ericglod/Density_bining/binDensityMP.py", line 687, in densityBin
    valmask)
  File "/home/ericglod/Density_bining/binDensityMP.py", line 1549, in _parallellize_depth_interpolation
    s_s_ = np.ctypeslib.as_ctypes(s_s)
  File "/home/ericglod/PCMDI_Metrics/PCMDI_METRICS/lib/python2.7/site-packages/numpy/ctypeslib.py", line 415, 
in as_ctypes
    raise TypeError("strided arrays not supported")
TypeError: strided arrays not supported

**Comment by momipsl** [comment]
Just committed a patch to resolve this.  It seems that the input array s_s is strided, i..e the result of a transposition.  This causes np.ctypeslib.as_ctypes(s_s) to fail.  Workaround is to use a copy of the array.  If the other input arrays szm_ & zzm_ are also strided then they will also have to be copied.

**Comment by eguil** [comment]
actually s_s (target density grid) is a lonN*LatN replicate of the same 
1D vertical vector, if that can help to simplify things. I made it like 
this so that we could do a matrix computation.

On 10/3/15 13:59, Mark A. Greenslade wrote:
>
> Just committed a patch to resolve this. It seems that the input array 
> s_s is strided, i..e the result of a transposition. This causes 
> np.ctypeslib.as_ctypes(s_s) to fail. Workaround is to use a copy of 
> the array. If the other input arrays szm_ & zzm_ are also strided then 
> they will also have to be copied.
>
> â
> Reply to this email directly or view it on GitHub 
> <https://github.com/eguil/Density_bining/issues/37#issuecomment-78047779>.
>

-- 
Eric Guilyardi
IPSL/LOCEAN - Dir. Rech. CNRS
Tour 45, 4eme, piece 406
UPMC, case 100
4 place Jussieu, F-75252 Paris
Tel: +33 (0)1 44 27 70 76 	Prof. Eric Guilyardi
NCAS Climate
Meteorology Department
University of Reading
Reading RG6 6BB - UK
Tel: +44 (0)118 378 8315

                 http://ncas-climate.nerc.ac.uk/~ericg

**Comment by eguil** [comment]
result of patch: =>> PBS: job killed: vmem 24252403712 exceeded limit 12884901888

**Comment by momipsl** [comment]
It would be helpful if you could get vmdm dumps at lines 1544 and 1563.  This will tell us whether copying the arrays c1m, c2m, s_s, szm & zzm to shared memory is inflating vmdm usage.  If not then it must be in the spawned processes.

**Comment by eguil** [comment]
Hi mark, what is a "vmdm" dump and how can I get it ?

On 11/3/15 15:31, Mark A. Greenslade wrote:
>
> It would be helpful if you could get vmdm dumps at lines 1544 and 
> 1563. This will tell us whether copying the arrays c1m, c2m, s_s, szm 
> & zzm to shared memory is inflating vmdm usage. If not then it must be 
> in the spawned processes.
>
> â
> Reply to this email directly or view it on GitHub 
> <https://github.com/eguil/Density_bining/issues/37#issuecomment-78273887>.
>

-- 
Eric Guilyardi
IPSL/LOCEAN - Dir. Rech. CNRS
Tour 45, 4eme, piece 406
UPMC, case 100
4 place Jussieu, F-75252 Paris
Tel: +33 (0)1 44 27 70 76 	Prof. Eric Guilyardi
NCAS Climate
Meteorology Department
University of Reading
Reading RG6 6BB - UK
Tel: +44 (0)118 378 8315

                 http://ncas-climate.nerc.ac.uk/~ericg

**Comment by momipsl** [comment]
Sorry this is a typo.  It should have read vmem, i.e. virtual memory dump.   I have just committed a change that outputs to stdout memory usage using the python resource module.

**Comment by eguil** [comment]
Here is the output:

   Total volume in z coordinates source grid (ref = 1.33 e+18) : 
1.31679820735e+18
   Mean Temp./Salinity in z coordinates source grid            : 
3.32230840011 34.7277874016
binDensityMP.INFO :: depth interpolation :: memory usage :: initial :: 
2669204 (kb)
binDensityMP.INFO :: depth interpolation :: memory usage :: array 
conversions step 1 - completed :: 2669204 (kb)
binDensityMP.INFO :: depth interpolation :: memory usage :: array 
conversions step 2 - completed :: 2669204 (kb)
binDensityMP.INFO :: depth interpolation :: memory usage :: completed :: 
2669204 (kb)
binDensityMP.INFO :: depth interpolation :: memory usage :: initial :: 
2669204 (kb)
binDensityMP.INFO :: depth interpolation :: memory usage :: array 
conversions step 1 - completed :: 2669204 (kb)
binDensityMP.INFO :: depth interpolation :: memory usage :: array 
conversions step 2 - completed :: 2669204 (kb)
binDensityMP.INFO :: depth interpolation :: memory usage :: completed :: 
2669204 (kb)
binDensityMP.INFO :: depth interpolation :: memory usage :: initial :: 
2669204 (kb)
binDensityMP.INFO :: depth interpolation :: memory usage :: array 
conversions step 1 - completed :: 2669204 (kb)
binDensityMP.INFO :: depth interpolation :: memory usage :: array 
conversions step 2 - completed :: 2669204 (kb)
binDensityMP.INFO :: depth interpolation :: memory usage :: completed :: 
2669204 (kb)
binDensityMP.INFO :: depth interpolation :: memory usage :: initial :: 
2669204 (kb)
binDensityMP.INFO :: depth interpolation :: memory usage :: array 
conversions step 1 - completed :: 2669204 (kb)
binDensityMP.INFO :: depth interpolation :: memory usage :: array 
conversions step 2 - completed :: 2669204 (kb)
binDensityMP.INFO :: depth interpolation :: memory usage :: completed :: 
2669204 (kb)
binDensityMP.INFO :: depth interpolation :: memory usage :: initial :: 
2669204 (kb)
binDensityMP.INFO :: depth interpolation :: memory usage :: array 
conversions step 1 - completed :: 2669204 (kb)
binDensityMP.INFO :: depth interpolation :: memory usage :: array 
conversions step 2 - completed :: 2669204 (kb)
binDensityMP.INFO :: depth interpolation :: memory usage :: completed :: 
2669204 (kb)
binDensityMP.INFO :: depth interpolation :: memory usage :: initial :: 
2669204 (kb)
binDensityMP.INFO :: depth interpolation :: memory usage :: array 
conversions step 1 - completed :: 2669204 (kb)
binDensityMP.INFO :: depth interpolation :: memory usage :: array 
conversions step 2 - completed :: 2669204 (kb)
binDensityMP.INFO :: depth interpolation :: memory usage :: completed :: 
2669204 (kb)
binDensityMP.INFO :: depth interpolation :: memory usage :: initial :: 
2669204 (kb)
binDensityMP.INFO :: depth interpolation :: memory usage :: array 
conversions step 1 - completed :: 2669204 (kb)
binDensityMP.INFO :: depth interpolation :: memory usage :: array 
conversions step 2 - completed :: 2669204 (kb)
binDensityMP.INFO :: depth interpolation :: memory usage :: completed :: 
2669204 (kb)
binDensityMP.INFO :: depth interpolation :: memory usage :: initial :: 
2669204 (kb)
binDensityMP.INFO :: depth interpolation :: memory usage :: array 
conversions step 1 - completed :: 2669204 (kb)
binDensityMP.INFO :: depth interpolation :: memory usage :: array 
conversions step 2 - completed :: 2669204 (kb)
binDensityMP.INFO :: depth interpolation :: memory usage :: completed :: 
2669204 (kb)
binDensityMP.INFO :: depth interpolation :: memory usage :: initial :: 
2669204 (kb)
binDensityMP.INFO :: depth interpolation :: memory usage :: array 
conversions step 1 - completed :: 2669204 (kb)
binDensityMP.INFO :: depth interpolation :: memory usage :: array 
conversions step 2 - completed :: 2669204 (kb)
=>> PBS: job killed: vmem 24195518464 exceeded limit 12884901888
Epilogue Args:
Job ID: 278207.cicladpbs6.private.ipsl.fr
User ID: ericglod
Group ID: ipsl
Job Name: script_qsub_parallel
Session ID: 15983
Resource List: 
mem=10gb,neednodes=1:ppn=1,nodes=1:ppn=1,vmem=12gb,walltime=02:00:00
Resources Used: 
cput=00:03:44,mem=18854296kb,vmem=23631316kb,walltime=00:09:51
Queue Name: short
Running Host: ciclad5.private.ipsl.fr


On 10/3/15 13:59, Mark A. Greenslade wrote:
>
> Just committed a patch to resolve this. It seems that the input array 
> s_s is strided, i..e the result of a transposition. This causes 
> np.ctypeslib.as_ctypes(s_s) to fail. Workaround is to use a copy of 
> the array. If the other input arrays szm_ & zzm_ are also strided then 
> they will also have to be copied.
>
> â
> Reply to this email directly or view it on GitHub 
> <https://github.com/eguil/Density_bining/issues/37#issuecomment-78047779>.
>

-- 
Eric Guilyardi
IPSL/LOCEAN - Dir. Rech. CNRS
Tour 45, 4eme, piece 406
UPMC, case 100
4 place Jussieu, F-75252 Paris
Tel: +33 (0)1 44 27 70 76 	Prof. Eric Guilyardi
NCAS Climate
Meteorology Department
University of Reading
Reading RG6 6BB - UK
Tel: +44 (0)118 378 8315

                 http://ncas-climate.nerc.ac.uk/~ericg

**Comment by momipsl** [comment]
How many cores did this job have access to?

**Comment by eguil** [comment]
one for now - I am first testing with one core one cpu before increasing 
them

On 12/3/15 09:13, Mark A. Greenslade wrote:
>
> How many cores did this job have access to?
>
> â
> Reply to this email directly or view it on GitHub 
> <https://github.com/eguil/Density_bining/issues/37#issuecomment-78438729>.
>

-- 
Eric Guilyardi
IPSL/LOCEAN - Dir. Rech. CNRS
Tour 45, 4eme, piece 406
UPMC, case 100
4 place Jussieu, F-75252 Paris
Tel: +33 (0)1 44 27 70 76 	Prof. Eric Guilyardi
NCAS Climate
Meteorology Department
University of Reading
Reading RG6 6BB - UK
Tel: +44 (0)118 378 8315

                 http://ncas-climate.nerc.ac.uk/~ericg

**Comment by momipsl** [comment]
This is designed to run on multiple cores.  If there is only one core then you will see no benefits as the value of MAX_PROCESSES in line 1581 will be set to 1.  In this scenario the job will only be able to spawn a single sub-process which defeats the purpose of the exercise.

I have updated the code to run sequentially if the number of cores is <= 2 (this leaves one core for system tasks).  So you need at least 3 cores before the depth interpolation are run in parallel

**Comment by eguil** [comment]
ok - I will try again

On 12/3/15 09:33, Mark A. Greenslade wrote:
>
> This is designed to run on multiple cores. If there is only one core 
> then you will see no benefits as the value of MAX_PROCESSES in line 
> 1581 will be set to 1. In this scenario the job will only be able to 
> spawn a single sub-process which defeats the purpose of the exercise.
>
> I have updated the code to run sequentially if the number of cores is 
> <= 2 (this leaves one core for system tasks). So you need at least 3 
> cores before the depth interpolation are run in parallel
>
> â
> Reply to this email directly or view it on GitHub 
> <https://github.com/eguil/Density_bining/issues/37#issuecomment-78440785>.
>

-- 
Eric Guilyardi
IPSL/LOCEAN - Dir. Rech. CNRS
Tour 45, 4eme, piece 406
UPMC, case 100
4 place Jussieu, F-75252 Paris
Tel: +33 (0)1 44 27 70 76 	Prof. Eric Guilyardi
NCAS Climate
Meteorology Department
University of Reading
Reading RG6 6BB - UK
Tel: +44 (0)118 378 8315

                 http://ncas-climate.nerc.ac.uk/~ericg

**Comment by eguil** [comment]
Here is the ouput with us 3 cores:

binDensityMP.INFO :: depth interpolation :: EXECUTING IN PARALLEL
binDensityMP.INFO :: depth interpolation :: memory usage :: initial :: 
2674972 (kb)
binDensityMP.INFO :: depth interpolation :: memory usage :: array 
conversions step 1 - completed :: 2674972 (kb)
binDensityMP.INFO :: depth interpolation :: memory usage :: array 
conversions step 2 - completed :: 2674972 (kb)
binDensityMP.INFO :: depth interpolation :: process pool created: 
max-processes = 7
binDensityMP.INFO :: depth interpolation :: memory usage :: completed :: 
2674972 (kb)
binDensityMP.INFO :: depth interpolation :: EXECUTING IN PARALLEL
binDensityMP.INFO :: depth interpolation :: memory usage :: initial :: 
2674972 (kb)
binDensityMP.INFO :: depth interpolation :: memory usage :: array 
conversions step 1 - completed :: 2674972 (kb)
binDensityMP.INFO :: depth interpolation :: memory usage :: array 
conversions step 2 - completed :: 2674972 (kb)
=>> PBS: job killed: vmem 24101470208 exceeded limit 12884901888


On 12/3/15 09:33, Mark A. Greenslade wrote:
>
> This is designed to run on multiple cores. If there is only one core 
> then you will see no benefits as the value of MAX_PROCESSES in line 
> 1581 will be set to 1. In this scenario the job will only be able to 
> spawn a single sub-process which defeats the purpose of the exercise.
>
> I have updated the code to run sequentially if the number of cores is 
> <= 2 (this leaves one core for system tasks). So you need at least 3 
> cores before the depth interpolation are run in parallel
>
> â
> Reply to this email directly or view it on GitHub 
> <https://github.com/eguil/Density_bining/issues/37#issuecomment-78440785>.
>

-- 
Eric Guilyardi
IPSL/LOCEAN - Dir. Rech. CNRS
Tour 45, 4eme, piece 406
UPMC, case 100
4 place Jussieu, F-75252 Paris
Tel: +33 (0)1 44 27 70 76 	Prof. Eric Guilyardi
NCAS Climate
Meteorology Department
University of Reading
Reading RG6 6BB - UK
Tel: +44 (0)118 378 8315

                 http://ncas-climate.nerc.ac.uk/~ericg

**Comment by durack1** [comment]
This may be relevant in #33
