### ISSUE TITLE
drive_density.py tweaks for ciclad

### ISSUE THREAD

**Issue by durack1** [eguil/Density_bining#41]
@eguil can you provide a ciclad path to data and also the machine full name ciclad.blah.blah.fr and I'll bolt this into drive_density.py as I make tweaks for the piControl experiment runs..

**Comment by eguil** [comment]
examples of files and path names

modelSo = '/prodigfs/esg/xml/CMIP5/piControl/ocean/mon/so/cmip5.CSIRO-Mk3-6-0.piControl.r1i1p1.mon.ocean.Omon.so.latest.xml'
modelThetao = '/prodigfs/esg/xml/CMIP5/piControl/ocean/mon/thetao/cmip5.CSIRO-Mk3-6-0.piControl.r1i1p1.mon.ocean.Omon.thetao.latest.xml'
modelAreacello = '/prodigfs/esg/xml/CMIP5/piControl/ocean/fx/areacello/cmip5.CSIRO-Mk3-6-0.piControl.r0i0p0.fx.ocean.fx.areacello.latest.xml'

**Comment by eguil** [comment]
Machine hostname: ciclad-ng.private.ipsl.fr
