### ISSUE TITLE
Project density analysis back to z

### ISSUE THREAD

**Issue by durack1** [eguil/Density_bining#46]
Use the insitu pressure to map back to a standard depth coord - suggest WOA levels (33)

**Comment by eguil** [comment]
Does this requires working on the full 4D fields ? Zonal mean T and depth do not account for local non-linear correlations... This question could also apply to ToE calculation. Needs more thinking.

**Comment by durack1** [comment]
@eguil this is a discover by doing question I think.. We had a machine failure whilst I was away so it might take a week or so to get back up to speed..

**Comment by eguil** [comment]
@durack1 More thinking following discussion with a colleague: in the lat/rho space, use the volume=f(depth) of the target grid to find the depth of isopynals using the volume of isopycnals (starting from top or bottom). Use an intermediate grid of say 5m (or fraction of WOA z grid) for precision (and then project back onto WOA grid).

**Comment by eguil** [comment]
Done by Yona
