### ISSUE TITLE
NaN vs. 1.e20 issue on ciclad with CDMS

### ISSUE THREAD

**Issue by eguil** [eguil/Density_bining#64]
- mme_ave_msk.py is creating files with NaNf instead of 1.e20 for valmask.
- Using the exact same files and python routines on Eric's mac does not produce this problem
- Try reinstalling CMDS via metrics package on ciclad.

**Comment by durack1** [comment]
@eguil let me know about this because it could be a cdms bug and we'll need to create an issue in that repo - note that the latest version of CDMS is 2.12 (see https://anaconda.org/conda-forge/cdms2/files?channel=main)

I have had issues in the past with regard to `NaN` numpy values

**Comment by eguil** [comment]
Installed on Eric's mac cdms2, cdutil etc. via `conda install <pckg> -c conda-forge` for local testing vs. ciclad
