### ISSUE TITLE
Check units in WOA file

### ISSUE THREAD

**Issue by eguil** [eguil/Density_bining#80]
area unit wrong (km2 rather than m2),
check scale factors

**Comment by durack1** [comment]
@eguil yep, it seems there are mixed units, just need to change the order of magnitude of https://github.com/eguil/Density_bining/blob/master/obs/make_areacello.py#L31

**Comment by durack1** [comment]
@eguil 
```
netcdf \190501_1007_WOD18_masks_0p25deg {
dimensions:
        depth = 137 ;
        bound = 2 ;
        latitude = 720 ;
        longitude = 1440 ;
variables:
...
        float basinmask3_area(latitude, longitude) ;
                basinmask3_area:_FillValue = 1.e+20f ;
                basinmask3_area:missing_value = 1.e+20f ;
                basinmask3_area:earthLandAreaM2 = 148940000000000. ;
                basinmask3_area:oceanSurfaceAreaM2 = 352342040224260. ; <- 352.3 x 10^12 m2
                basinmask3_area:earthWaterAreaM2 = 361132000000000. ;
                basinmask3_area:earthSurfaceAreaM2 = 510100000000000. ;
                basinmask3_area:units = "m^2" ;
```

**Comment by durack1** [comment]
@eguil @ysilvy there should be two PRs (Pull Requests) ready for either of you to merge that resolves both issues - I've left them as unmerged PRs so you can double check this solves the two issues

**Comment by durack1** [comment]
FYI they're at https://github.com/eguil/Density_bining/pull/82 and https://github.com/eguil/Density_bining/pull/83 respectively
